/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PropiedadDao;
import controlador.listas.ListaEnlazada;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import modelo.Propiedad;
import vista.Utilidades.Utilidades;

/**
 *
 * @author LENOVO
 */
public class FrmPrincipal extends javax.swing.JFrame {
    PropiedadDao propiedadDao = new PropiedadDao();
    Propiedad aux = new Propiedad();
    Integer iterador = 1;
    public static ListaEnlazada<Propiedad> PropiedadDatos = new ListaEnlazada<>();
    

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/recursos/favicon.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        btnPropiedad1 = new javax.swing.JButton();
        btnPropiedad2 = new javax.swing.JButton();
        btnPropiedad4 = new javax.swing.JButton();
        btnPropiedad3 = new javax.swing.JButton();
        btnPropiedad5 = new javax.swing.JButton();
        btnPropiedad6 = new javax.swing.JButton();
        btnPropiedad7 = new javax.swing.JButton();
        btnPropiedad8 = new javax.swing.JButton();
        btnPropiedad9 = new javax.swing.JButton();
        btnPropiedad10 = new javax.swing.JButton();
        btnPropiedad11 = new javax.swing.JButton();
        btnPropiedad12 = new javax.swing.JButton();
        btnPropiedad16 = new javax.swing.JButton();
        btnPropiedad15 = new javax.swing.JButton();
        btnPropiedad14 = new javax.swing.JButton();
        btnPropiedad13 = new javax.swing.JButton();
        btnCuentas = new javax.swing.JButton();
        btnIngresarNuevaPropiedad = new javax.swing.JButton();
        btnAdministrarPropiedades = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnPagos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/AIRBNB1.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Lupa Busqueda.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        btnPropiedad1.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro1\\Img1pro1.png")); // NOI18N
        btnPropiedad1.setBorder(null);
        btnPropiedad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad1ActionPerformed(evt);
            }
        });

        btnPropiedad2.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro2\\img1pro2.png")); // NOI18N
        btnPropiedad2.setBorder(null);
        btnPropiedad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad2ActionPerformed(evt);
            }
        });

        btnPropiedad4.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro4\\img1pro4.png")); // NOI18N
        btnPropiedad4.setBorder(null);
        btnPropiedad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad4ActionPerformed(evt);
            }
        });

        btnPropiedad3.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro3\\img1pro3.png")); // NOI18N
        btnPropiedad3.setBorder(null);
        btnPropiedad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad3ActionPerformed(evt);
            }
        });

        btnPropiedad5.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro5\\img1pro5.png")); // NOI18N
        btnPropiedad5.setBorder(null);
        btnPropiedad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad5ActionPerformed(evt);
            }
        });

        btnPropiedad6.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad6.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro6\\img1pro6.png")); // NOI18N
        btnPropiedad6.setBorder(null);
        btnPropiedad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad6ActionPerformed(evt);
            }
        });

        btnPropiedad7.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad7.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro7\\img1pro7.png")); // NOI18N
        btnPropiedad7.setBorder(null);
        btnPropiedad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad7ActionPerformed(evt);
            }
        });

        btnPropiedad8.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad8.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro8\\img1pro8.png")); // NOI18N
        btnPropiedad8.setBorder(null);
        btnPropiedad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad8ActionPerformed(evt);
            }
        });

        btnPropiedad9.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lettc\\OneDrive\\Desktop\\Tercer Ciclo\\ARREGLADO\\Alquiler de Propiedades (4)\\Alquiler de Propiedades\\ImgPropiedades\\pro9\\img1pro9.png")); // NOI18N
        btnPropiedad9.setBorder(null);
        btnPropiedad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad9ActionPerformed(evt);
            }
        });

        btnPropiedad10.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad10.setBorder(null);
        btnPropiedad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad10ActionPerformed(evt);
            }
        });

        btnPropiedad11.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad11.setBorder(null);
        btnPropiedad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad11ActionPerformed(evt);
            }
        });

        btnPropiedad12.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad12.setBorder(null);
        btnPropiedad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad12ActionPerformed(evt);
            }
        });

        btnPropiedad16.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad16.setBorder(null);
        btnPropiedad16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad16ActionPerformed(evt);
            }
        });

        btnPropiedad15.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad15.setBorder(null);
        btnPropiedad15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad15ActionPerformed(evt);
            }
        });

        btnPropiedad14.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad14.setBorder(null);
        btnPropiedad14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad14ActionPerformed(evt);
            }
        });

        btnPropiedad13.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedad13.setBorder(null);
        btnPropiedad13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropiedad13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPropiedad9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnPropiedad10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPropiedad11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPropiedad12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPropiedad13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPropiedad14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPropiedad15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPropiedad16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPropiedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnPropiedad2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnPropiedad3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPropiedad4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPropiedad5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPropiedad6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnPropiedad7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPropiedad8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPropiedad2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPropiedad7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPropiedad5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPropiedad6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPropiedad8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPropiedad10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPropiedad9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPropiedad11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPropiedad12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPropiedad13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropiedad16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel4);

        btnCuentas.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnCuentas.setForeground(new java.awt.Color(0, 0, 102));
        btnCuentas.setText("Cuentas");
        btnCuentas.setBorder(null);
        btnCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasActionPerformed(evt);
            }
        });

        btnIngresarNuevaPropiedad.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnIngresarNuevaPropiedad.setForeground(new java.awt.Color(0, 0, 102));
        btnIngresarNuevaPropiedad.setText("Ingresar Propiedad");
        btnIngresarNuevaPropiedad.setBorder(null);
        btnIngresarNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevaPropiedadActionPerformed(evt);
            }
        });

        btnAdministrarPropiedades.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnAdministrarPropiedades.setForeground(new java.awt.Color(0, 0, 102));
        btnAdministrarPropiedades.setText("Administrar Propiedades");
        btnAdministrarPropiedades.setBorder(null);
        btnAdministrarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarPropiedadesActionPerformed(evt);
            }
        });

        btnFavoritos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnFavoritos.setForeground(new java.awt.Color(0, 0, 102));
        btnFavoritos.setText("Favoritos");
        btnFavoritos.setBorder(null);
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });

        btnPagos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(0, 0, 102));
        btnPagos.setText("Pagos");
        btnPagos.setBorder(null);

        btnPagos1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagos1.setForeground(new java.awt.Color(0, 0, 102));
        btnPagos1.setText("SALIR");
        btnPagos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPagos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(btnIngresarNuevaPropiedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdministrarPropiedades, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarNuevaPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdministrarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga el contrato dentro de los botones
     */
    public void cargarContrato() {
        for (int i = 0; i < propiedadDao.listar().getTamanio(); i++) {
            if (propiedadDao.obtenerPropiedad(i) != null) {
                aux = propiedadDao.obtenerPropiedad(i);
                JButton btnPropiedad = new JButton();
                btnPropiedad.setBounds(2, 14, 3, 14);
                add(btnPropiedad);
                jPanel4.add(btnPropiedad);
                jPanel4.revalidate();
                jPanel4.repaint();
            }
            if (aux.getImg() != null) {
                Utilidades.DefinirImagenBoton(btnPropiedad1, aux.getImg());
            }
        }
    }
    private void btnIngresarNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevaPropiedadActionPerformed
        FrmIngresoDireccion Propiedadprincipal = new FrmIngresoDireccion();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIngresarNuevaPropiedadActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        FrmAgregarFavoritos Propiedadprincipal = new FrmAgregarFavoritos();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnPropiedad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad2ActionPerformed

            FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
            Propiedadprincipal.setVisible(true);
            this.dispose();


    }//GEN-LAST:event_btnPropiedad2ActionPerformed

    private void btnPropiedad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad1ActionPerformed
//        if (propiedadDao.obtenerPropiedad(iterador)!=null) {
//            aux = propiedadDao.obtenerPropiedad(iterador);
//        }
//        if (aux.getImg()!=null) {
//            Utilidades.DefinirImagenBoton(btnPropiedad1, aux.getImg());
//
//            iterador++;
//        }
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad1ActionPerformed

    private void btnPropiedad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad3ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad3ActionPerformed

    private void btnPropiedad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad4ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
       Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad4ActionPerformed

    private void btnPropiedad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad5ActionPerformed
       FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad5ActionPerformed

    private void btnPropiedad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad6ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad6ActionPerformed

    private void btnPropiedad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad7ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad7ActionPerformed

    private void btnPropiedad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad8ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad8ActionPerformed

    private void btnPropiedad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad9ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad9ActionPerformed

    private void btnPropiedad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad10ActionPerformed
       FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad10ActionPerformed

    private void btnPropiedad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad11ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad11ActionPerformed

    private void btnPropiedad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad12ActionPerformed
       FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad12ActionPerformed

    private void btnPropiedad13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad13ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad13ActionPerformed

    private void btnPropiedad14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad14ActionPerformed
       FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad14ActionPerformed

    private void btnPropiedad15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad15ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad15ActionPerformed

    private void btnPropiedad16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropiedad16ActionPerformed
        FrmContratoUsuario Propiedadprincipal = new FrmContratoUsuario();
        Propiedadprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPropiedad16ActionPerformed

    private void btnAdministrarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarPropiedadesActionPerformed
        FrmDescripcionPropiedad administrarPropiedades = new FrmDescripcionPropiedad();
        administrarPropiedades.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministrarPropiedadesActionPerformed

    private void btnPagos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagos1ActionPerformed
       FrmLogin login = new FrmLogin();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnPagos1ActionPerformed

    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed
        
    }//GEN-LAST:event_btnCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarPropiedades;
    private javax.swing.JButton btnCuentas;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnIngresarNuevaPropiedad;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnPagos1;
    private javax.swing.JButton btnPropiedad1;
    private javax.swing.JButton btnPropiedad10;
    private javax.swing.JButton btnPropiedad11;
    private javax.swing.JButton btnPropiedad12;
    private javax.swing.JButton btnPropiedad13;
    private javax.swing.JButton btnPropiedad14;
    private javax.swing.JButton btnPropiedad15;
    private javax.swing.JButton btnPropiedad16;
    private javax.swing.JButton btnPropiedad2;
    private javax.swing.JButton btnPropiedad3;
    private javax.swing.JButton btnPropiedad4;
    private javax.swing.JButton btnPropiedad5;
    private javax.swing.JButton btnPropiedad6;
    private javax.swing.JButton btnPropiedad7;
    private javax.swing.JButton btnPropiedad8;
    private javax.swing.JButton btnPropiedad9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
