/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.listas.Exepciones.ListaVaciaException;
import controlador.listas.Exepciones.PosicionNoEncontradaException;
import controlador.listas.ListaEnlazada;
import java.io.IOException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Contrato;
import modelo.MetodoPago;
import modelo.Propiedad;
import modelo.TipoDePago;
import vista.Utilidades.Utilidades;

/**
 *
 * @author Dennys
 */
public class FrmSeleccionTipoDePago extends javax.swing.JFrame {

    FrmPagos fPagoUnico = new FrmPagos();
    public static boolean verificadorPago;
    public static Integer verificadorMetodoDePago;
    Propiedad aux = new Propiedad();
    private ListaEnlazada<Propiedad> listaPropiedades;
    Contrato cont = new Contrato();
    /**
     * Creates new form FrmSeleccionTipoDePago
     */
    public FrmSeleccionTipoDePago() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/recursos/favicon.png")).getImage());
        this.setLocationRelativeTo(null);
    }


    
    /**
     * Crea un nuevo FrmSeleccionTipoDePago con un id unica para hacer
     * referencia a al contrato
     * @param id 
     */
    public FrmSeleccionTipoDePago(Integer id) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/recursos/favicon.png")).getImage());
        this.setLocationRelativeTo(null);
        try {
            listaPropiedades = Utilidades.cargarPropiedades();
            aux = listaPropiedades.obtener(id);
        } catch (Exception e) {
            System.out.println(e);
        }
        txtTotal.setEnabled(false);
        txtTotal.setText((Double.valueOf(aux.getPrecio()) * aux.getContrato().getNroDias()) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CbxTipoDePago = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selección Tipo De Pago"));

        jLabel1.setText("Bienvenido usuari@ a la ventana de Pagos:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección"));

        jLabel2.setText("Seleccione por favor el tipo de Pago que desea realizar:");

        CbxTipoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago a plazos", "Un solo Pago" }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(CbxTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel3.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try {
            if (!guardarPago()) {
                cargarVentana();
            } else {
                JOptionPane.showMessageDialog(null, "TODO CORRECTO", "Información", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                FrmPagoPlazos.verificador = null;
                FrmPagos.verificador = null;
                FrmPagoPlazos.verificador=null;
                FrmPagos.verificador=null;
                verificadorMetodoDePago=null;        
                FrmContratoUsuario fm = new FrmContratoUsuario();
                fm.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmContratoUsuario fm = new FrmContratoUsuario();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    /**
     * Permite mostrar una ventana dependiendo del tipo de pago que
     * seleccione el usuario
     */
    private void cargarVentana() {
        if (CbxTipoDePago.getSelectedItem().toString().equals("Pago a plazos")) {
            FrmPagoPlazos fpagosplazos = new FrmPagoPlazos(aux.getId()-1);
            fpagosplazos.setVisible(true);
            //this.dispose();
        } else {
            fPagoUnico.setVisible(true);
            //this.dispose();
        }
    }


    /**
     * Permite guardar el pago dependiendo de los verificadore enviados desde
     * los frames FrmPagoPlazos o FrmPago
     * @return boolean
     * @throws ListaVaciaException
     * @throws PosicionNoEncontradaException
     * @throws IOException 
     */
    private Boolean guardarPago() throws ListaVaciaException, PosicionNoEncontradaException, IOException {
        listaPropiedades=Utilidades.cargarPropiedades();
        aux = listaPropiedades.obtener(aux.getId()-1);
        
        cont = aux.getContrato();
        if (FrmPagoPlazos.verificador != null || FrmPagos.verificador != null) {
            if (FrmPagoPlazos.verificador || FrmPagos.verificador) {
                cont.getPago().setEstadoPago(true);
                if (CbxTipoDePago.getSelectedItem().toString().equals("Pago a plazos")) {
                    cont.getPago().setTipoDePago(TipoDePago.plazos);
                } else {
                    cont.getPago().setTipoDePago(TipoDePago.unSoloPago);
                }
                switch (verificadorMetodoDePago) {
                    case 1:
                        cont.getPago().setMetodoPago(MetodoPago.TarjetaDebito);
                        break;
                    case 2:
                        cont.getPago().setMetodoPago(MetodoPago.TarjetaCredito);
                        break;
                    case 3:
                        cont.getPago().setMetodoPago(MetodoPago.Transferencia);
                        break;
                    default:
                        throw new AssertionError();

                }
            }
            try {
                cont.setId(aux.getId());
                cont.getPago().setId(aux.getId());
                
                aux.setContrato(cont);
                System.out.println(aux.getContrato());
                generarAlquiler();
                listaPropiedades.modificarPoscicion(aux,aux.getId()-1);
                Utilidades.guardarPropiedades(listaPropiedades);
            } catch (Exception e) {
                System.out.println(e);
            }
            return true;
        }
        return false;
    }
    
    /**
     * Genera alquiler
     * @throws ParseException 
     */
    private void generarAlquiler() throws ParseException {
        Date aux1 = vista.Utilidades.Utilidades.obtenerDateofString(aux.getFechaIngreso());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(aux1);
        calendar.add(Calendar.DATE, aux.getContrato().getNroDias());
        Date nuevaFecha = calendar.getTime();
        aux.setFechaIngreso(vista.Utilidades.Utilidades.obtenerFechaFormateada(nuevaFecha));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionTipoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionTipoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionTipoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionTipoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeleccionTipoDePago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxTipoDePago;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
