/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import busqueda.controlador.LinealBinaria.BusquedaLinealBinaria;
import controlador.QuickSort.MetodoQuickSort;
import controlador.RolesController;
import controlador.listas.Exepciones.ListaVaciaException;
import controlador.listas.Exepciones.PosicionNoEncontradaException;
import controlador.listas.ListaEnlazada;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ordenacion.Excepciones.AtributoNoEncontradoException;
import vista.Modelo.ModeloTablaRoles;
import vista.Utilidades.Utilidades;

/**
 *
 * @author leomah
 */
public class RolesDialog extends javax.swing.JDialog {
    private ModeloTablaRoles mtr = new ModeloTablaRoles();
    private RolesController rolesController = new RolesController();

    /**
     * Creates new form RolesDialog
     */
    public RolesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarRoles();
        cargarTabla(rolesController);
        this.setLocationByPlatform(true);
    }
    
    private void cargarTabla(RolesController rc){
        mtr.setRc(rc);
        tblRoles.setModel(mtr);
        tblRoles.updateUI();
    }
    
    private void cargarRoles(){
        try {
            this.rolesController = Utilidades.cargarRoles();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado");
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buscar() throws AtributoNoEncontradoException, IllegalArgumentException, ListaVaciaException, PosicionNoEncontradaException, IllegalAccessException{
        cargarRoles();
        cargarTabla(rolesController);
        if (!txtBusqueda.getText().isEmpty() && (rbtnID.isSelected() || rbtnNombre.isSelected())) {
            BusquedaLinealBinaria blb = new BusquedaLinealBinaria();
            RolesController rcAux = new RolesController();
            ListaEnlazada<Integer> posAux = new ListaEnlazada<>();
            MetodoQuickSort mqs = new MetodoQuickSort();
            
            if(rbtnID.isSelected()) {
                posAux = blb.linealBinaria(rolesController.getListaRoles(), Integer.parseInt(txtBusqueda.getText()), "ID");
                rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "ID", MetodoQuickSort.ASCENDENTE));
            }else{
                posAux = blb.linealBinaria(rolesController.getListaRoles(), txtBusqueda.getText(), "nombre");
                rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "nombre", MetodoQuickSort.ASCENDENTE));
            }
                        
            for (int i = 0; i < posAux.getTamanio(); i++) {
                rcAux.getListaRoles().insertar(rolesController.getListaRoles().obtener(posAux.obtener(i)));
            }
            
            cargarTabla(rcAux);
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, brinde toda la información \nsolicitada para la búsqueda");
        }
    }
    
    private void eliminar() throws ListaVaciaException, PosicionNoEncontradaException, FileNotFoundException{
        if (tblRoles.getSelectedRow() >= 0) {
            rolesController.eliminarRol(tblRoles.getSelectedRow());
            Utilidades.guardarRoles(rolesController);
            cargarRoles();
            cargarTabla(rolesController);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un elemento");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        rbtnID = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoles = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAgregarRol = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnGuardarArchivo = new javax.swing.JMenuItem();
        btnCargarArchivo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnIDAscendente = new javax.swing.JMenuItem();
        btnIDDescendente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnNombreAscendente = new javax.swing.JMenuItem();
        btnNombreDescendente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 225));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("ROLES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Buscar:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 230, -1));

        rbtnID.setText("ID");
        rbtnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIDActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        rbtnNombre.setText("Nombre");
        jPanel2.add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 820, 90));

        tblRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRoles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 800, 340));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        btnAgregarRol.setText("AGREGAR");
        btnAgregarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        jMenu1.setText("Archivo");

        btnGuardarArchivo.setText("Guardar");
        jMenu1.add(btnGuardarArchivo);

        btnCargarArchivo.setText("Cargar");
        jMenu1.add(btnCargarArchivo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ordenar");

        jMenu3.setText("ID");

        btnIDAscendente.setText("Ascendente");
        btnIDAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDAscendenteActionPerformed(evt);
            }
        });
        jMenu3.add(btnIDAscendente);

        btnIDDescendente.setText("Descendente");
        btnIDDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDDescendenteActionPerformed(evt);
            }
        });
        jMenu3.add(btnIDDescendente);

        jMenu2.add(jMenu3);

        jMenu4.setText("Nombre");

        btnNombreAscendente.setText("Ascendente");
        btnNombreAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreAscendenteActionPerformed(evt);
            }
        });
        jMenu4.add(btnNombreAscendente);

        btnNombreDescendente.setText("Descendente");
        btnNombreDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreDescendenteActionPerformed(evt);
            }
        });
        jMenu4.add(btnNombreDescendente);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIDActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            buscar();
        } catch (AtributoNoEncontradoException ex) {
            Logger.getLogger(CuentasDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(CuentasDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaVaciaException ex) {
            Logger.getLogger(CuentasDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(CuentasDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(CuentasDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            // TODO add your handling code here:
            eliminar();
        } catch (ListaVaciaException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (tblRoles.getSelectedRow() >= 0) {
            RolDialog rd = new RolDialog(null, true, tblRoles.getSelectedRow(), rolesController);
            rd.setVisible(true);
            cargarRoles();
            cargarTabla(rolesController);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un elemento");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarRoles();
        cargarTabla(rolesController);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolActionPerformed
        // TODO add your handling code here:
        RolDialog rd = new RolDialog(null, true, null, rolesController);
        rd.setVisible(true);
        cargarRoles();
        cargarTabla(rolesController);
    }//GEN-LAST:event_btnAgregarRolActionPerformed

    private void btnIDAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDAscendenteActionPerformed
        try {
            // TODO add your handling code here:
            cargarRoles();
            cargarTabla(rolesController);
            MetodoQuickSort mqs = new MetodoQuickSort();
            rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "ID", MetodoQuickSort.ASCENDENTE));
            cargarTabla(rolesController);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AtributoNoEncontradoException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIDAscendenteActionPerformed

    private void btnIDDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDDescendenteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            cargarRoles();
            cargarTabla(rolesController);
            MetodoQuickSort mqs = new MetodoQuickSort();
            rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "ID", MetodoQuickSort.DESCENDENTE));
            cargarTabla(rolesController);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AtributoNoEncontradoException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIDDescendenteActionPerformed

    private void btnNombreAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreAscendenteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            cargarRoles();
            cargarTabla(rolesController);
            MetodoQuickSort mqs = new MetodoQuickSort();
            rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "nombre", MetodoQuickSort.ASCENDENTE));
            cargarTabla(rolesController);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AtributoNoEncontradoException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNombreAscendenteActionPerformed

    private void btnNombreDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreDescendenteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            cargarRoles();
            cargarTabla(rolesController);
            MetodoQuickSort mqs = new MetodoQuickSort();
            rolesController.setListaRoles(mqs.quickSort(rolesController.getListaRoles(), "nombre", MetodoQuickSort.DESCENDENTE));
            cargarTabla(rolesController);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AtributoNoEncontradoException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(RolesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNombreDescendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RolesDialog dialog = new RolesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarRol;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuItem btnCargarArchivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JMenuItem btnGuardarArchivo;
    private javax.swing.JMenuItem btnIDAscendente;
    private javax.swing.JMenuItem btnIDDescendente;
    private javax.swing.JButton btnModificar;
    private javax.swing.JMenuItem btnNombreAscendente;
    private javax.swing.JMenuItem btnNombreDescendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnID;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JTable tblRoles;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
